### ISSUE TITLE
Workers in /lib will not be automatically loaded in Rails app

### ISSUE THREAD

**Issue by bithavoc** [bithavoc/background_bunnies#1]
In a rails app, we need to uncomment `config.autoload_paths += %W(#{config.root}/lib}` from application.rb if we want the worker classes to be automatically loaded from `/lib`.

We need to find a workaround this or include the instruction in Readme.md

**Comment by guilleiguaran** [comment]
Actually, this happen with any class saved in `lib/` folder, you should add `lib/` to autoload_paths or require the file manually.

IMHO, this isn't a bug of the gem, is just the expected behaviour.

**Comment by bithavoc** [comment]
So it's mandatory to add `lib/` to auto_load_paths? 

Do you have a suggestion to load the classes without having to add autoload libs?

Have a look to: 
https://github.com/heapsource/background_bunnies/blob/master/lib/background_bunnies.rb#L80

Ideally the user of the gem will inspect classes inside the module `BackgroundBunnies::Workers` and it should be loaded by the gem automatically regardless it's a Rails app or not.
